version: "3.7"

services:
  rr_app:
    build:
      context: .
      dockerfile: ./docker/containers/api.Dockerfile
    container_name: 'rr_app'
    volumes:
      - .:/application
    env_file:
        - ./docker/envs/.env
    ports:
      - "7072:7070"
    networks:
      - app
    depends_on:
      - db

  bot:
    build:
      context: .
      dockerfile: docker/containers/bot.Dockerfile
    container_name: 'rr_bot-1'
    env_file: ./docker/envs/.env
    volumes:
      - .:/application
#    ports:
#      -
    networks:
      - app
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3311:3306"
    env_file:
      - ./docker/envs/.env
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
      - app
    volumes:
      - db_data:/var/lib/mysql

networks:
  app:
    driver: bridge

volumes:
  db_data: