"""empty message

Revision ID: 3790cc196655
Revises: 0e95b8bee677
Create Date: 2021-12-20 21:43:17.575317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3790cc196655'
down_revision = '0e95b8bee677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('visitors_need_help')
    op.drop_table('visitors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_first_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_last_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('date_time', sa.DATE(), nullable=True),
    sa.Column('user_phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('visitors_need_help',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_full_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('date_time', sa.DATE(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('category')
    # ### end Alembic commands ###